version: '3.8'

services:
  web:
    build: .
    command: gunicorn -b 0.0.0.0:5000 app:app
    volumes:
      - .:/app
      - db_data:/app/instance  # Mount the volume for SQLite database
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production

volumes:
  db_data: